config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :fonts
  resources :titles
  resources :colors
  get 'dashboards/index'
  match 'change_styling', to: 'dashboards#change_styling', via: [:get, :post, :update]

  root to: 'dashboards#index'

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/color.rb
class Color < ApplicationRecord
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
	belongs_to :user
end

app/models/font.rb
class Font < ApplicationRecord
end

app/models/title.rb
class Title < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :dashboard       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    if resource.admin?
	  colors_path
	else
	  root_path	
	end
  end

end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
  before_action :set_color, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :check_authorization

  # GET /colors
  # GET /colors.json
  def index
    @colors = Color.all
  end

  # GET /colors/1
  # GET /colors/1.json
  def show
  end

  # GET /colors/new
  def new
    @color = Color.new
  end

  # GET /colors/1/edit
  def edit
  end

  # POST /colors
  # POST /colors.json
  def create
    @color = Color.new(color_params)

    respond_to do |format|
      if @color.save
        format.html { redirect_to @color, notice: 'Color was successfully created.' }
        format.json { render :show, status: :created, location: @color }
      else
        format.html { render :new }
        format.json { render json: @color.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colors/1
  # PATCH/PUT /colors/1.json
  def update
    respond_to do |format|
      if @color.update(color_params)
        format.html { redirect_to @color, notice: 'Color was successfully updated.' }
        format.json { render :show, status: :ok, location: @color }
      else
        format.html { render :edit }
        format.json { render json: @color.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colors/1
  # DELETE /colors/1.json
  def destroy
    @color.destroy
    respond_to do |format|
      format.html { redirect_to colors_url, notice: 'Color was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def check_authorization
      if !current_user.admin?
        flash[:alert] = "You are not authorised!!!"
        redirect_to root_path
      end  
      #raise "You are not authorised!!" unless current_user.admin?
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_color
      @color = Color.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def color_params
      params.require(:color).permit(:name)
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def index
  	
  end

  def change_styling
  	if current_user.dashboard.blank? 
  	  dashboard = current_user.build_dashboard(dashboard_params)
      dashboard.save
    else
      current_user.dashboard.update(dashboard_params)
    end  
    flash[:notice] = 'Successfully Changed Styling.'
    redirect_to root_path
  end

  private

  def dashboard_params
    params.require(:dashboard).permit(:color, :title, :font, :user_id)
  end	
end

app/controllers/fonts_controller.rb
class FontsController < ApplicationController
  before_action :set_font, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :check_authorization

  # GET /fonts
  # GET /fonts.json
  def index
    @fonts = Font.all
  end

  # GET /fonts/1
  # GET /fonts/1.json
  def show
  end

  # GET /fonts/new
  def new
    @font = Font.new
  end

  # GET /fonts/1/edit
  def edit
  end

  # POST /fonts
  # POST /fonts.json
  def create
    @font = Font.new(font_params)

    respond_to do |format|
      if @font.save
        format.html { redirect_to @font, notice: 'Font was successfully created.' }
        format.json { render :show, status: :created, location: @font }
      else
        format.html { render :new }
        format.json { render json: @font.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fonts/1
  # PATCH/PUT /fonts/1.json
  def update
    respond_to do |format|
      if @font.update(font_params)
        format.html { redirect_to @font, notice: 'Font was successfully updated.' }
        format.json { render :show, status: :ok, location: @font }
      else
        format.html { render :edit }
        format.json { render json: @font.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fonts/1
  # DELETE /fonts/1.json
  def destroy
    @font.destroy
    respond_to do |format|
      format.html { redirect_to fonts_url, notice: 'Font was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def check_authorization
      if !current_user.admin?
        flash[:alert] = "You are not authorised!!!"
        redirect_to root_path
      end  
      #raise "You are not authorised!!" unless current_user.admin?
    end 

    # Use callbacks to share common setup or constraints between actions.
    def set_font
      @font = Font.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def font_params
      params.require(:font).permit(:font)
    end
end

app/controllers/titles_controller.rb
class TitlesController < ApplicationController
  before_action :set_title, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :check_authorization

  # GET /titles
  # GET /titles.json
  def index
    @titles = Title.all
  end

  # GET /titles/1
  # GET /titles/1.json
  def show
  end

  # GET /titles/new
  def new
    @title = Title.new
  end

  # GET /titles/1/edit
  def edit
  end

  # POST /titles
  # POST /titles.json
  def create
    @title = Title.new(title_params)

    respond_to do |format|
      if @title.save
        format.html { redirect_to @title, notice: 'Title was successfully created.' }
        format.json { render :show, status: :created, location: @title }
      else
        format.html { render :new }
        format.json { render json: @title.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /titles/1
  # PATCH/PUT /titles/1.json
  def update
    respond_to do |format|
      if @title.update(title_params)
        format.html { redirect_to @title, notice: 'Title was successfully updated.' }
        format.json { render :show, status: :ok, location: @title }
      else
        format.html { render :edit }
        format.json { render json: @title.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /titles/1
  # DELETE /titles/1.json
  def destroy
    @title.destroy
    respond_to do |format|
      format.html { redirect_to titles_url, notice: 'Title was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def check_authorization
      if !current_user.admin?
        flash[:alert] = "You are not authorised!!!"
        redirect_to root_path
      end  
      #raise "You are not authorised!!" unless current_user.admin?
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_title
      @title = Title.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def title_params
      params.require(:title).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
	def get_colors
		Color.all.pluck(:name)
	end	
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/fonts_helper.rb
module FontsHelper
	def get_fonts
		Font.all.pluck(:font)
	end	
end

app/helpers/titles_helper.rb
module TitlesHelper
	def get_titles
		Title.all.pluck(:title)
	end
end

app/views/colors/_form.html.erb
<%= form_for(color) do |f| %>
  <% if color.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(color.errors.count, "error") %> prohibited this color from being saved:</h2>

      <ul>
      <% color.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit "Create", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/colors/edit.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="panel panel-default">
	  <div class="panel-heading">
	    <h3 class="panel-title">Editing Color</h3>
	  </div>
	  <div class="panel-body">
	  	<div class="panel-body">
		  	<%= link_to 'Back', colors_path, class: 'pull-right btn btn-default' %>
		  	<%= link_to 'Show', @color, class: 'btn btn-success' %>
		  	<div class="clearfix"></div>
		    <%= render 'form', color: @color %>
		</div>
	  </div>
	</div>
</div>

app/views/colors/index.html.erb
<% if notice %>
  <div class="col-md-6 col-md-offset-3">
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  </div>
<% end %>

<div class="col-md-6 col-md-offset-3">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Colours</h3>
    </div>
    <div class="panel-body">
      <table class="table table-stripped table-bordered">
        <thead>
          <tr>
            <th>Name</th>
            <th colspan="3">Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @colors.each do |color| %>
            <tr>
              <td><%= color.name %></td>
              <td><%= link_to 'Show', color %></td>
              <td><%= link_to 'Edit', edit_color_path(color) %></td>
              <td><%= link_to 'Destroy', color, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to 'New Color', new_color_path, class: 'btn btn-success' %>
    </div>
  </div>
</div>

app/views/colors/new.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="panel panel-default">
	  <div class="panel-heading">
	    <h3 class="panel-title">New Color</h3>
	  </div>
	  <div class="panel-body">
	  	<%= link_to 'Back', colors_path, class: 'pull-right btn btn-default' %>
	  	<div class="clearfix"></div>
	    <%= render 'form', color: @color %>
	  </div>
	</div>
</div>

app/views/colors/show.html.erb
<% if notice %>
  <div class="col-md-6 col-md-offset-3">
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  </div>
<% end %>

<div class="col-md-6 col-md-offset-3">
	<div class="panel panel-default">
	  <div class="panel-heading">
	    <h3 class="panel-title">Show Color</h3>
	  </div>
	  <div class="panel-body">
	    <div class="form-group">
	    	<label>Name</label>
	    	<div class="form-field">
	  			<%= @color.name %>  		
	    	</div>
	    </div>
	  </div>
	  	<div class="panel-footer">
	    <%= link_to 'Edit', edit_color_path(@color), class: 'btn btn-primary' %>
		<%= link_to 'Back', colors_path, class: 'btn btn-default' %>
	  </div>
	</div>
</div>

app/views/dashboards/index.html.erb
<% if notice %>
  <div class="col-md-6 col-md-offset-3">
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  </div>
<% end %>
<% if alert %>
  <div class="col-md-6 col-md-offset-3">
    <div class="alert alert-warning" role="alert">
      <%= alert %>
    </div>
  </div>
<% end %>

<div class="col-md-6 col-md-offset-3">
	<div class="panel panel-default">
	  <div class="panel-heading">
	    <h3 class="panel-title">Change Styling</h3>
	  </div>
	  <div class="panel-body">
	  	<%= form_for :dashboard, :url => change_styling_path do |f| %>
		  <div class="form-group">
		    <%= f.label :color %>
		    <%= f.select :color, get_colors, class:'form-control', include_blank: "Select" %>
		  </div>
		  <div class="form-group">
		    <%= f.label :title %>
		    <%= f.select :title, get_titles, class:'form-control', include_blank: "Select" %>
		  </div>
		  <div class="form-group">
		    <%= f.label :font %>
		    <%= f.select :font, get_fonts, class:'form-control', include_blank: "Select" %>
		  </div>
		  <div class="form-group">
		    <%= f.submit 'Submit', class: 'btn btn-primary' %>
		  </div>
		<% end %>
	  </div>
	</div>
</div>

<div class="col-md-6 col-md-offset-3">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= current_user.dashboard.title if current_user.dashboard.present? %></h3>
    </div>
    <div class="panel-body">
      <div style="color: <%= current_user.dashboard.color if current_user.dashboard.present? %>; font-family: <%= current_user.dashboard.font if current_user.dashboard.present? %>">
      	This is the test
      </div>
    </div>
  </div>
</div>

app/views/fonts/_form.html.erb
<%= form_for(font) do |f| %>
  <% if font.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(font.errors.count, "error") %> prohibited this font from being saved:</h2>

      <ul>
      <% font.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :font %>
    <%= f.text_field :font, class:'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/fonts/edit.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="panel panel-default">
	  <div class="panel-heading">
	    <h3 class="panel-title">Editing Font</h3>
	  </div>
	  <div class="panel-body">
	    <%= render 'form', font: @font %>
	  </div>
	  	<div class="panel-footer">
	    <%= link_to 'Show', @font, class: 'btn btn-success' %>
		<%= link_to 'Back', fonts_path, class: 'btn btn-default' %>
	  </div>
	</div>
</div>

app/views/fonts/index.html.erb
<% if notice %>
  <div class="col-md-6 col-md-offset-3">
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  </div>
<% end %>

<div class="col-md-6 col-md-offset-3">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Fonts</h3>
    </div>
    <div class="panel-body">
      <table class="table table-stripped table-bordered">
        <thead>
          <tr>
            <th>Font</th>
            <th colspan="3">Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @fonts.each do |font| %>
            <tr>
              <td><%= font.font %></td>
              <td><%= link_to 'Show', font %></td>
              <td><%= link_to 'Edit', edit_font_path(font) %></td>
              <td><%= link_to 'Destroy', font, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to 'New Font', new_font_path, class: 'btn btn-success' %>
    </div>
  </div>
</div>

app/views/fonts/new.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="panel panel-default">
	  <div class="panel-heading">
	    <h3 class="panel-title">New Font</h3>
	  </div>
	  <div class="panel-body">
	    <%= render 'form', font: @font %>
	  </div>
	  <div class="panel-footer">
		<%= link_to 'Back', fonts_path, class: 'btn btn-default' %>
	  </div>
	</div>
</div>

app/views/fonts/show.html.erb
<% if notice %>
  <div class="col-md-6 col-md-offset-3">
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  </div>
<% end %>

<div class="col-md-6 col-md-offset-3">
	<div class="panel panel-default">
	  <div class="panel-heading">
	    <h3 class="panel-title">Show Font</h3>
	  </div>
	  <div class="panel-body">
	    <div class="form-group">
	    	<label>Font</label>
	    	<div class="form-field">
	  			<%= @font.font %>  		
	    	</div>
	    </div>
	  </div>
	  	<div class="panel-footer">
	    <%= link_to 'Edit', edit_font_path(@font), class: 'btn btn-primary' %>
		<%= link_to 'Back', fonts_path, class: 'btn btn-default' %>
	  </div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="<%= dashboards_index_path %>">Travel Tripper</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <% if current_user.present? %>
	      	<% if current_user.admin? %>  	
		      <ul class="nav navbar-nav">
		        <li class="active"><a href="<%= colors_path %>">Colors</a></li>
	            <li><a href="<%= titles_path %>">Titles</a></li>
	            <li><a href="<%= fonts_path %>">Fonts</a></li>
		      </ul>
		    <% end %>
		    <ul class="nav navbar-nav navbar-right">
		        <li class="dropdown">
		          <a href="#" class=" pull-right dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %><span class="caret"></span></a>
		          <ul class="dropdown-menu">
		            <li><a href="<%= destroy_user_session_path %>">Log out</a></li>
		          </ul>
		        </li>
		    </ul>
	      <% end %>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>
    
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div style="margin-top: 100px;">
  		<%= yield %>	
  	</div>
    
  </body>
</html>

app/views/titles/_form.html.erb
<%= form_for(title) do |f| %>
  <% if title.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(title.errors.count, "error") %> prohibited this title from being saved:</h2>

      <ul>
      <% title.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class:'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/titles/edit.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="panel panel-default">
	  <div class="panel-heading">
	    <h3 class="panel-title">Editing Title</h3>
	  </div>
	  <div class="panel-body">
	    <%= render 'form', title: @title %>
	  </div>
	  	<div class="panel-footer">
	    <%= link_to 'Show', @title, class: 'btn btn-success' %>
		<%= link_to 'Back', titles_path, class: 'btn btn-default' %>
	  </div>
	</div>
</div>

app/views/titles/index.html.erb
<% if notice %>
  <div class="col-md-6 col-md-offset-3">
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  </div>
<% end %>

<div class="col-md-6 col-md-offset-3">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Titles</h3>
    </div>
    <div class="panel-body">
      <table class="table table-stripped table-bordered">
        <thead>
          <tr>
            <th>Title</th>
            <th colspan="3">Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @titles.each do |title| %>
            <tr>
              <td><%= title.title %></td>
              <td><%= link_to 'Show', title %></td>
              <td><%= link_to 'Edit', edit_title_path(title) %></td>
              <td><%= link_to 'Destroy', title, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to 'New Title', new_title_path, class: 'btn btn-success' %>
    </div>
  </div>
</div>

app/views/titles/new.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="panel panel-default">
	  <div class="panel-heading">
	    <h3 class="panel-title">New Title</h3>
	  </div>
	  <div class="panel-body">
	    <%= render 'form', title: @title %>
	  </div>
	  <div class="panel-footer">
		<%= link_to 'Back', titles_path, class: 'btn btn-default' %>
	  </div>
	</div>
</div>

app/views/titles/show.html.erb
<% if notice %>
  <div class="col-md-6 col-md-offset-3">
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  </div>
<% end %>

<div class="col-md-6 col-md-offset-3">
	<div class="panel panel-default">
	  <div class="panel-heading">
	    <h3 class="panel-title">Show Title</h3>
	  </div>
	  <div class="panel-body">
	    <div class="form-group">
	    	<label>Title</label>
	    	<div class="form-field">
	  			<%= @title.title %>  		
	    	</div>
	    </div>
	  </div>
	  	<div class="panel-footer">
	    <%= link_to 'Edit', edit_title_path(@title), class: 'btn btn-primary' %>
		<%= link_to 'Back', titles_path, class: 'btn btn-default' %>
	  </div>
	</div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>